### ISSUE TITLE
Crash at init and at Vacuum.start service call:

### ISSUE THREAD

**Issue by tmenguy** [galletn/iaqualink#25]
Hi,

Just adding in case you never seen it 

On latest HA, latest iAqualink : 

- At init: 

Logger: homeassistant.components.websocket_api.http.connection
Source: components/websocket_api/commands.py:241
integration: Home Assistant WebSocket API ([documentation](https://www.home-assistant.io/integrations/websocket_api), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+websocket_api%22))
First occurred: July 4, 2024 at 11:59:12 PM (2 occurrences)
Last logged: July 4, 2024 at 11:59:55 PM

[281472418726384] Unexpected exception
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 241, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2731, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2774, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 999, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1071, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/config/custom_components/iaqualinkRobots/vacuum.py", line 186, in async_start
    data = await self.setCleanerState(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/iaqualinkRobots/vacuum.py", line 393, in setCleanerState
    return message.json()
           ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/http_websocket.py", line 121, in json
    return loads(self.data)
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/__init__.py", line 339, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not int

- at start call:
- Logger: homeassistant.core
Source: core.py:2751
First occurred: July 4, 2024 at 11:58:10 PM (1 occurrences)
Last logged: July 4, 2024 at 11:58:10 PM

Error executing service: <ServiceCall vacuum.start (c:01J1ZVG67CYWGD2YNJ2N6RK6KY): entity_id=['vacuum.peyrebelle_pool_robot']>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/core.py", line 2751, in _run_service_call_catch_exceptions
    await coro_or_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 2774, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 999, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1071, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/config/custom_components/iaqualinkRobots/vacuum.py", line 186, in async_start
    data = await self.setCleanerState(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/iaqualinkRobots/vacuum.py", line 393, in setCleanerState
    return message.json()
           ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/http_websocket.py", line 121, in json
    return loads(self.data)
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/__init__.py", line 339, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not int

**Comment by tmenguy** [comment]
Robot : RA 6900 iQ
Well connected and accessible

**Comment by galletn** [comment]
are you running the latest version of the code?

**Comment by galletn** [comment]
or did you try to run the cleaning before it got populated? did not try to break it yet myself 🤕

**Comment by tmenguy** [comment]
Hi, yes latest code. I exposed the vacuum to homekit through the HA HomeKit integration, maybe it was from here

**Comment by tmenguy** [comment]
I'll see when I can reproduce those it I see a pattern ....

**Comment by galletn** [comment]
any update?

**Comment by galletn** [comment]
reminder ... trying to keep the list clean
