### ISSUE TITLE
Update for vacuum.peyrebelle_pool_robot fails

### ISSUE THREAD

**Issue by tmenguy** [galletn/iaqualink#26]
Hi,

sorry again, another one:

Logger: homeassistant.helpers.entity
Source: helpers/entity.py:944
First occurred: July 4, 2024 at 11:46:06 PM (15 occurrences)
Last logged: 11:34:10 AM

Update for vacuum.peyrebelle_pool_robot fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 944, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1296, in async_device_update
    await self.async_update()
  File "/config/custom_components/iaqualinkRobots/vacuum.py", line 248, in async_update
    self._status = data['payload']['robot']['state']['reported']['aws']['status']
                   ~~~~~~~~~~~~~~~^^^^^^^^^
KeyError: 'robot'

**Comment by tmenguy** [comment]
Robot : RA 6900 iQ
Well connected and accessible

**Comment by galletn** [comment]
would you maybe be able to change your password and send me over your credentials to nicolas.gallet@skynet.be ?

I think I will be able to quick fix it if I see what is returned in your case as the other models seem to work fine so far with the code.

**Comment by tmenguy** [comment]
Hi, 

I’m out for 2 weeks will see when coming back, thanks for the support !

Thomas

**Comment by galletn** [comment]
should be fixed with the new code, added another try catch on that part can you confirm?

**Comment by tmenguy** [comment]
fantastic, will try asap ...

**Comment by galletn** [comment]
any update on this one?

**Comment by tmenguy** [comment]
hey sorry about not coming back : I don't have the HA error above anymore .. I do have some timeout to get the status of the robot (see below) but I do thinks this particular issue can be closed ! thanks a lot!



logger: homeassistant.helpers.entity
Source: helpers/entity.py:942
First occurred: 5:51:08 PM (1 occurrences)
Last logged: 5:51:08 PM

Update for vacuum.peyrebelle_pool_robot fails
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/asyncio/tasks.py", line 520, in wait_for
    return await fut
           ^^^^^^^^^
  File "/config/custom_components/iaqualinkRobots/vacuum.py", line 465, in get_device_status
    message = await websocket.receive()
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/client_ws.py", line 314, in receive
    msg = await self._reader.read()
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/streams.py", line 681, in read
    return await super().read()
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/streams.py", line 640, in read
    await self._waiter
asyncio.exceptions.CancelledError

**Comment by tmenguy** [comment]
oh no it is back:

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 942, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1300, in async_device_update
    await self.async_update()
  File "/config/custom_components/iaqualinkRobots/vacuum.py", line 312, in async_update
    self._status = data['payload']['robot']['state']['reported']['aws']['status']

**Comment by tmenguy** [comment]
Forked the project and I a tried to debug…. But couldn’t reproduce for now (obviously :) ). But seeing the code it can be normal to crash here as the retry is not protected . Will see if I had time to issue a PR to protect it a bit more.

**Comment by galletn** [comment]
Any update @tmenguy ?

**Comment by galletn** [comment]
any update @tmenguy ?

**Comment by tmenguy** [comment]
sorry on other project ... when I'll get too annoyed by the error in my HA logs I'll fix it :)

**Comment by CLARENNE-Q** [comment]
I had this issue too and it's because i have 2 devices on my iaqua account.

**Comment by galletn** [comment]
must have been then because its not consistently returning the devices in the same order, should have been fixed then with the update of @CLARENNE-Q to ignore other devices instead of skipping first device. There is no clear specs so 👍 🤦 

@tmenguy can you confirm then we can close this issue
