### ISSUE TITLE
Status not updating and start/stop command not working

### ISSUE THREAD

**Issue by justinmaiuto** [galletn/iaqualink#28]
This was working well for a few days but now the status is stuck on cleaning and he start/stop buttons give the following error

I've tried restarting with not luck.

```
[139713914131008] Unexpected exception
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 241, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2731, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2774, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 999, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1071, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/config/custom_components/iaqualinkRobots/vacuum.py", line 202, in async_stop
    data = await self.setCleanerState(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/iaqualinkRobots/vacuum.py", line 393, in setCleanerState
    return message.json()
           ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/http_websocket.py", line 121, in json
    return loads(self.data)
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/__init__.py", line 339, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not NoneType
```

**Comment by galletn** [comment]
hi @justinmaiuto I was running a newer version locally already with a bit more timeout and connection closures.

Can you update to the latest version and retest?

**Comment by galletn** [comment]
@justinmaiuto update?

**Comment by justinmaiuto** [comment]
Sorry! Yep working
