### ISSUE TITLE
Unable to update plugin via HACS

### ISSUE THREAD

**Issue by chansearrington** [galletn/iaqualink#31]
Hey @galletn,

Thanks for your work on this.

For some reason iaqualink is the only HACS plugin that I have that can't be updated through the Home Assistant UI.

I have to uninstall and then reinstall through HACS with each update.

I've attached the following screenshots with the final showing the error message that Home Assistant displays.

![CleanShot 2024-07-26 at 14 48 00@2x](https://github.com/user-attachments/assets/d89c762d-8f17-4dd5-a311-c33463f00828)

And here is the detail from the error generated in the log.

`Logger: homeassistant.components.websocket_api.http.connection
Source: components/websocket_api/commands.py:241
integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 2:47:58 PM (2 occurrences)

Last logged: 2:52:00 PM

[140582331245632] Unexpected exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/homeassistant/components/websocket_api/commands.py", line 241, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/homeassistant/core.py", line 2731, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/homeassistant/core.py", line 2774, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/homeassistant/helpers/service.py", line 999, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/homeassistant/helpers/service.py", line 1071, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/homeassistant/components/update/__init__.py", line 154, in async_install
    await entity.async_install_with_progress(version, backup)
  File "/usr/local/lib/python3.12/site-packages/homeassistant/components/update/__init__.py", line 458, in async_install_with_progress
    await self.async_install(version, backup)
  File "/config/custom_components/hacs/update.py", line 111, in async_install
    await self._ensure_capabilities(version)
  File "/config/custom_components/hacs/update.py", line 95, in _ensure_capabilities
    raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: The version cfcedea for this integration can not be used with HACS.`

**Comment by galletn** [comment]
hi @chansearrington, can you try updating from the HACS screen instead of the settings -> updates one?

test it out just now and worked like a charm.

![image](https://github.com/user-attachments/assets/b13a0e89-bc3a-452b-ad52-775c3163a287)

**Comment by chansearrington** [comment]
@galletn where is that option? I don't see an "update" option in HACS

![CleanShot 2024-07-27 at 14 43 16@2x](https://github.com/user-attachments/assets/d46699c4-8837-42be-8f21-8357aadaa982)

**Comment by galletn** [comment]
You ca do it from here:

<img width="1341" alt="image" src="https://github.com/user-attachments/assets/09837561-50ce-4e11-b6c4-12bd6709123a">

or one further in the integrations screen:

![image](https://github.com/user-attachments/assets/7cdf06de-8053-4fd3-9430-4f5514db2811)

**Comment by chansearrington** [comment]
I don't have that in my HACS setup. I'm not sure why. I assume it's because I'm running Home Assistant in a docker container and not a OS/Supervisor?

Regardless, this is the only HACS integration I've seen that won't update via the normal process.

**Comment by ppastur** [comment]
I have HA on Docker and mine updates in the same way as shown above by @galletn

**Comment by galletn** [comment]
@chansearrington can you make sure you have latest versions of HACS / HA / ... I did not see any others with issues so far so hard to reproduce / fix this one

**Comment by galletn** [comment]
hi @chansearrington can you check again, made sure it works on HACS 2.0.0 too!
